project:
  name: customer_churn_prediction
  owner: data_science_team
  environment: production
  description: Predict customer churn for telecom users

mlflow:
  experiment_name: customer_churn_experiments
  experiment_id: NA
  track_params: true
  track_metrics: true
  track_artifacts:
    - feature_config
    - preprocessing_objects
    - model

  tags:
    project: churn
    stage: production
    owner: data_science_team


dataset:
  dataset_name: telecom_churn_v1
  random_state: 52
  # test_size: .3
  
  # todo: Add train test split ratio in future if test dataset is not provided.
  train:
    type: csv
    path: data/raw/churn_train.csv
    id_column: CustomerID
    target_column: Churn
    positive_class: 1

  # test:
  #   type: csv
  #   path: data/raw/churn_test.csv
  #   id_column: CustomerID
  #   target_column: Churn
  #   positive_class: 1


pipeline:
  - name: rename_cols
    type: rename_columns
    params:
      mapping:
        cust_id: customer_id
        "Contract Length": contract_length

  - name: cast_types
    type: type_cast
    params:
      columns:
        age: int
        income: float

  # Todo: Add column wise different strategy for missing value imputation in future.
  # Currently using mean for every numerical column
  - name: missing
    type: missing_values
    params:
      strategy: mean

  # Todo: Add column wise different strategy for missing value imputation in future.
  - name: cleaning
    type: cleaning
    params:
      replacements:
        country:
          America: USA

  # Todo: Add column wise different strategy for missing value imputation in future.
  # Currently using mean for every numerical column
  - name: encoding
    type: encoding
    params:
      Gender:
        method: onehot

  - name: encoding
    type: encoding
    params:
      contract_length: ## This names should be the one which are renamed.
        method: ordinal

  # Todo: Add column wise different strategy for missing value imputation in future.
  # Currently using standard scaler for every numerical column
  - name: scaling
    type: scaling
    params:
      method: standard

features:
  scaling: standard

model:
  type: logistic_regression
  hyperparameters:
    C: 1.0
    max_iter: 100


training:
  objective: binary:logistic


evaluation:
  metrics:
    - accuracy
    - f1